# Generated by Django 4.1.7 on 2023-10-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_empleado', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('domicilio', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('unidad', models.CharField(max_length=100)),
                ('antiguedad', models.PositiveIntegerField()),
                ('rfc', models.CharField(max_length=13)),
                ('curp', models.CharField(max_length=18)),
            ],
        ),
    ]
