# Generated by Django 4.1.7 on 2023-10-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quincenas', models.IntegerField()),
            ],
        ),
    ]
