# Generated by Django 4.1.7 on 2023-10-11 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0002_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fideicomisos_backend.empleado'),
        ),
    ]
