# Generated by Django 4.1.7 on 2023-10-27 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0003_prestamo_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionParentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Esposo', 'Esposo'), ('Hijo', 'Hijo')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fideicomisos_backend.empleado'),
        ),
    ]
