# Generated by Django 4.1.7 on 2023-11-06 18:17

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0004_relacionparentesco_alter_prestamo_empleado'),
    ]

    operations = [

        migrations.CreateModel(
            name='SeguroVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_fallecimiento', models.DateTimeField()),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('beneficiario', models.CharField(max_length=100)),
            ],
        ),
    ]
