# Generated by Django 4.1.7 on 2023-11-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0006_segurovida_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='fideicomisos_backend.empleado'),
        ),
        migrations.AlterField(
            model_name='segurovida',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguros_vida', to='fideicomisos_backend.empleado'),
        ),
    ]
