# Generated by Django 4.1.7 on 2023-11-29 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0007_alter_prestamo_empleado_alter_segurovida_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastosFunerarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padre', models.BooleanField(default=False)),
                ('madre', models.BooleanField(default=False)),
                ('esposo', models.BooleanField(default=False)),
                ('hijo', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_funerarios', to='fideicomisos_backend.empleado')),
            ],
        ),
    ]
