# Generated by Django 4.1.7 on 2023-11-29 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0008_gastosfunerarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoAprobado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quincenas', models.IntegerField()),
                ('fecha_aprobacion', models.DateField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fideicomisos_backend.empleado')),
            ],
        ),
    ]
