# Generated by Django 4.1.7 on 2023-12-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0009_prestamoaprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
