# Generated by Django 4.1.7 on 2023-12-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0010_prestamo_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamoaprobado',
            name='apellido_materno_empleado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prestamoaprobado',
            name='apellido_paterno_empleado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prestamoaprobado',
            name='nombre_empleado',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
