# Generated by Django 4.1.7 on 2023-12-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0011_prestamoaprobado_apellido_materno_empleado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelacionParentesco',
        ),
        migrations.AlterField(
            model_name='gastosfunerarios',
            name='esposo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='gastosfunerarios',
            name='hijo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='gastosfunerarios',
            name='madre',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='gastosfunerarios',
            name='padre',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
