# Generated by Django 4.1.7 on 2023-12-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0012_delete_relacionparentesco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='cantidad1',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='cantidad2',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fideicomisos_backend.empleado'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='quincenas',
            field=models.IntegerField(choices=[(1, 'Opción 1'), (2, 'Opción 2')]),
        ),
    ]
