# Generated by Django 4.1.7 on 2023-12-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0014_rename_cantidad1_prestamoaprobado_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='cantidad',
            field=models.CharField(max_length=15),
        ),
    ]
