# Generated by Django 4.1.7 on 2023-12-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0015_alter_prestamo_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='cantidad',
            field=models.CharField(choices=[('5000', '$5,000.00'), ('10000', '$10,000.00'), ('15000', '$15,000.00'), ('20000', '$20,000.00')], max_length=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='quincenas',
            field=models.CharField(choices=[('24', '24'), ('48', '48')], max_length=2),
        ),
    ]
