# Generated by Django 4.1.7 on 2023-12-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0016_alter_prestamo_cantidad_alter_prestamo_quincenas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='cantidad',
            field=models.CharField(choices=[(1, '$5,000.00'), (2, '$10,000.00'), (3, '$15,000.00'), (4, '$20,000.00')], max_length=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='quincenas',
            field=models.CharField(choices=[(1, '24'), (2, '48')], max_length=2),
        ),
    ]
