# Generated by Django 4.1.7 on 2023-12-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0018_alter_prestamo_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='quincenas',
            field=models.CharField(choices=[('24', '24'), ('48', '48')], max_length=2),
        ),
    ]
