# Generated by Django 4.1.7 on 2023-12-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0019_alter_prestamo_quincenas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='cantidad',
            field=models.CharField(choices=[('$5,000.00', '$5,000.00'), ('$10,000.00', '$10,000.00'), ('$15,000.00', '$15,000.00'), ('$20,000.00', '$20,000.00')], max_length=10),
        ),
    ]
