# Generated by Django 4.1.7 on 2023-12-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0021_remove_gastosfunerarios_esposo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosfunerarios',
            name='parentesco',
            field=models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Esposo', 'Esposo'), ('Hijo', 'Hijo')], max_length=10, null=True),
        ),
    ]
