# Generated by Django 4.1.7 on 2023-12-08 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0022_alter_gastosfunerarios_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='fideicomisos_backend.empleado'),
        ),
    ]
