# Generated by Django 4.1.7 on 2023-12-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0024_alter_prestamoaprobado_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='estatus',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
