# Generated by Django 4.1.7 on 2024-03-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0026_prestamo_pagoporquincena'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamoaprobado',
            name='pago_por_quincena',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
