# Generated by Django 4.1.7 on 2024-04-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0027_prestamoaprobado_pago_por_quincena'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GastosFunerarios',
        ),
    ]
