# Generated by Django 4.1.7 on 2024-04-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0029_gastosfunerarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Esposo', 'Esposo'), ('Hijo', 'Hijo')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='gastosfunerarios',
            name='parentesco',
        ),
        migrations.AddField(
            model_name='gastosfunerarios',
            name='parentescos',
            field=models.ManyToManyField(to='fideicomisos_backend.parentesco'),
        ),
    ]
