# Generated by Django 4.1.7 on 2024-04-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0030_parentesco_remove_gastosfunerarios_parentesco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastosfunerarios',
            name='parentescos',
        ),
        migrations.AddField(
            model_name='gastosfunerarios',
            name='parentesco',
            field=models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Esposo', 'Esposo'), ('Hijo', 'Hijo')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Parentesco',
        ),
    ]
