# Generated by Django 4.1.7 on 2024-04-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0033_rename_parentescos_gastosfunerarios_parentesco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastosfunerarios',
            name='parentesco',
        ),
        migrations.DeleteModel(
            name='Parentesco',
        ),
        migrations.AddField(
            model_name='gastosfunerarios',
            name='parentesco',
            field=models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Esposo', 'Esposo'), ('Hijo', 'Hijo')], max_length=10, null=True),
        ),
    ]
