# Generated by Django 4.1.7 on 2024-04-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0039_gastosfunerarios_parentesco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastosfunerarios',
            name='parentesco',
        ),
    ]
