# Generated by Django 4.1.7 on 2024-08-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0041_remove_gastosfunerarios_parentescos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='empleado',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='empleado_n_empleado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='n_empleado',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
