# Generated by Django 4.1.7 on 2024-08-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0042_remove_prestamo_empleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='empleado_n_empleado',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='numero_empleado',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
