# Generated by Django 4.1.7 on 2024-08-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0043_remove_prestamo_empleado_n_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='numero_empleado',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
