# Generated by Django 4.1.7 on 2024-08-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0045_alter_prestamo_numero_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
