# Generated by Django 4.1.7 on 2024-08-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0046_empleado_direccion_alter_empleado_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
