# Generated by Django 4.1.7 on 2024-08-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0048_empleado_nombre_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='antiguedad',
        ),
    ]
