# Generated by Django 4.1.7 on 2024-08-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0049_remove_empleado_antiguedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='numero_empleado',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamo', to='fideicomisos_backend.empleado'),
        ),
    ]
