# Generated by Django 4.1.7 on 2024-08-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0051_rename_nombre_empleado_nombres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='apellido_materno',
            new_name='apellidoMaterno',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='apellido_paterno',
            new_name='apellidoPaterno',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='n_empleado',
            new_name='numeroEmpleado',
        ),
    ]
