# Generated by Django 4.1.7 on 2024-08-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0052_rename_apellido_materno_empleado_apellidomaterno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='telefono',
            new_name='telefono1',
        ),
    ]
