# Generated by Django 4.1.7 on 2024-08-12 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0053_rename_telefono_empleado_telefono1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='fideicomisos_backend.empleado'),
        ),
    ]
