# Generated by Django 4.1.7 on 2024-08-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0055_alter_prestamo_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segurovida',
            name='beneficiario',
        ),
        migrations.RemoveField(
            model_name='segurovida',
            name='fecha_fallecimiento',
        ),
        migrations.AddField(
            model_name='segurovida',
            name='apellido_materno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='segurovida',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='segurovida',
            name='esposo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='segurovida',
            name='hijo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='segurovida',
            name='madre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='segurovida',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='segurovida',
            name='padre',
            field=models.BooleanField(default=False),
        ),
    ]
