# Generated by Django 4.1.7 on 2024-08-13 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0057_segurovida_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segurovida',
            old_name='field',
            new_name='porcentaje',
        ),
    ]
