# Generated by Django 4.1.7 on 2024-08-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0059_remove_segurovida_domicilio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='empleado',
            new_name='empleado_n_empleado',
        ),
    ]
