# Generated by Django 4.1.7 on 2024-08-14 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0060_rename_empleado_prestamo_empleado_n_empleado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='empleado_n_empleado',
            new_name='empleado',
        ),
    ]
