# Generated by Django 4.1.7 on 2024-08-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0061_rename_empleado_n_empleado_prestamo_empleado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoAprobado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=10)),
                ('quincenas', models.IntegerField()),
                ('pago_por_quincena', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_aprobacion', models.DateField(auto_now_add=True)),
                ('nombre_empleado', models.CharField(blank=True, max_length=100)),
                ('apellido_paterno_empleado', models.CharField(blank=True, max_length=100)),
                ('apellido_materno_empleado', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
