# Generated by Django 4.1.7 on 2024-08-16 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0063_alter_prestamo_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='fecha_ingreso',
            new_name='fechaIngreso',
        ),
    ]
