# Generated by Django 4.1.7 on 2024-08-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0064_rename_fecha_ingreso_empleado_fechaingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='fecha_nacimiento',
            new_name='fechaNacimiento',
        ),
    ]
