# Generated by Django 4.1.7 on 2024-08-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0066_alter_empleado_correo_alter_empleado_curp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono1',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='unidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
