# Generated by Django 4.1.7 on 2024-08-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0067_alter_empleado_curp_alter_empleado_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='unidad',
            new_name='direccionGeneral',
        ),
    ]
