# Generated by Django 4.1.7 on 2024-08-19 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0068_rename_unidad_empleado_direcciongeneral'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamoaprobado',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamo_aprobado', to='fideicomisos_backend.empleado'),
        ),
    ]
