# Generated by Django 4.1.7 on 2024-08-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0069_prestamoaprobado_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamoaprobado',
            name='empleado',
        ),
    ]
