# Generated by Django 4.1.7 on 2024-08-19 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0070_remove_prestamoaprobado_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamoaprobado',
            name='empleado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fideicomisos_backend.empleado'),
        ),
    ]
