# Generated by Django 4.1.7 on 2024-08-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0071_prestamoaprobado_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='jubilacionSolicitada',
            field=models.BooleanField(default=False),
        ),
    ]
