# Generated by Django 4.1.7 on 2024-08-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0072_empleado_jubilacionsolicitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='telefono1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
