# Generated by Django 4.1.7 on 2024-08-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideicomisos_backend', '0073_alter_empleado_telefono1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='telefono1',
            field=models.CharField(blank=True, default='Sin registro', max_length=15, null=True),
        ),
    ]
